### ISSUE TITLE
XMPlaneTransform(Stream) parameter rename to clarify usage

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXMath#10]
DirectXMath has a `XMPlaneTransform` and `XMPlaneTransformStream`, but for the special case of Inverse(M) = M, it can be made more efficient.

**Comment by walbourn** [comment]
The existing ``XMPlaneTransform`` (and the stream variant) assumes your are passing it the inverse transpose. Most people probably expect it to do that for them, so it 'seems' broken on non-rotation matrices.

The solution is to make the existing ``XMPlaneTransform`` and  ``XMPlaneTransformStream`` do the inverse transpose, and add  ``XMPlaneTransformOrthoganal`` and ``XMPlaneTransformOrthoganalStream`` to do what it's currently doing.

**Comment by shawnhar** [comment]
Are you proposing a breaking change to the existing API?

**Comment by walbourn** [comment]
The naming makes sense, but I agree breaking changes are to be avoided.

I think the reality is that the person who originally proposed ``XMPlaneTransformOrthogonal`` probably thought that ``XMPlaneTransform`` did the inverse-transpose for you...

It might make more sense to have a new ``XMPlaneInverseTransposeTransform`` that did the inverse & transpose for you as part of the transform, but I think the general point of the function not doing that is to make it clear that it's expensive.

Maybe I'll just settle for better docs and perhaps change the name of the parameter in the header to make it clearer that it takes an inverse transpose:

    XMVECTOR    XM_CALLCONV     XMPlaneTransform(FXMVECTOR P, FXMMATRIX ITM);

**Comment by walbourn** [comment]
See https://github.com/microsoft/DirectXMath/commit/332fb99d07d64f3b4fa89fafb4f303b758420749
