### ISSUE TITLE
Convert all typedef to using

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXMath#113]
Still have some lingering C style ``typdef``. Should use C++ style ``using`` instead.

**Comment by john-h-k** [comment]
looks pretty trivial, can I take this? 😄

**Comment by walbourn** [comment]
``using`` is better for simple alias names like:

```
using XMVECTOR = __m128;
```

It cannot be used however to define const versions of types like:

```
typedef const XMVECTOR& HXMVECTOR;
```

So in the end I just cleaned up *some* of the ``typedef`` usage.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXMath/commit/13069ff5589144c39fe3791f287f0cd9ebf822ff)
