### ISSUE TITLE
XMQuaternionSquad param name and doc needs clarification

### ISSUE THREAD

**Issue by alek314** [microsoft/DirectXMath#117]
Hi!
  Currently, the signature of XMQuaternionSquad is:
XMQuaternionSquad( FXMVECTOR Q0,  FXMVECTOR Q1,  FXMVECTOR Q2,  GXMVECTOR Q3,    float  t)
which is misleading because acording to  [https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dxquaternionsquad](url),
the param list should be ( FXMVECTOR Q1,  FXMVECTOR A,  FXMVECTOR B,  GXMVECTOR C,    float  t)

  Here is my test case , a modified version from [https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dxquaternionsquadsetup](url):

    XMVECTOR Q0 = XMVectorSet(0,  0, 0.707f, -.707f);
    XMVECTOR Q1 = XMVectorSet(0,  0, 0.000f, 1.000f);
    XMVECTOR Q2 = XMVectorSet(0,  0, 0.707f, 0.707f);
    XMVECTOR Q3 = XMVectorSet(0,  0, 1.000f, 0.000f);
    XMVECTOR A, B, C;
    XMQuaternionSquadSetup(&A, &B, &C, Q0, Q1, Q2, Q3);
    XMVECTOR result = XMQuaternionSquad(Q1, A, B, C, 0.5);
    XMVECTOR axis;
    float angle;
    XMQuaternionToAxisAngle(&axis, &angle, result);

which is 45 degree rotation around z axis

P.S. 
Please consider adding a sample like above to the doc, should be helpful to others.
Thank you!

**Comment by walbourn** [comment]
Thanks for the suggestion. Filed a [PR](https://github.com/MicrosoftDocs/sdk-api/pull/800).

> Note you can submit PRs to Microsoft Docs directly if you want.
