### ISSUE TITLE
Comment does not match with actual code?

### ISSUE THREAD

**Issue by zznewclear13** [microsoft/DirectXMath#145]
Our left handed perspective matrix should be like this:

<img src="https://latex.codecogs.com/svg.image?\begin{bmatrix}\frac{1}{tan(\frac{fovy}{2})&space;\cdot&space;\frac{x}{y}}&space;&&space;0&space;&&space;0&space;&&space;0&space;\\0&space;&&space;\frac{1}{tan(\frac{fovy}{2})}&space;&&space;0&space;&&space;0&space;\\0&space;&&space;0&space;&&space;\frac{far}{far&space;-&space;near}&space;&&space;1&space;\\0&space;&&space;0&space;&&space;-\frac{far&space;\cdot&space;near}{far&space;-&space;near}&space;&&space;0&space;\\\end{bmatrix}" title="\begin{bmatrix}\frac{1}{tan(\frac{fovy}{2}) \cdot \frac{x}{y}} & 0 & 0 & 0 \\0 & \frac{1}{tan(\frac{fovy}{2})} & 0 & 0 \\0 & 0 & \frac{far}{far - near} & 1 \\0 & 0 & -\frac{far \cdot near}{far - near} & 0 \\\end{bmatrix}" />

But the comments in [DirectXMathMatrix.inl#L2518-L2521](https://github.com/microsoft/DirectXMath/blob/ecc6560c14fbba13149c72ddcafacb14cb84e599/Inc/DirectXMathMatrix.inl#L2518-L2521) seem to indicate the projection matrix is:

<img src="https://latex.codecogs.com/svg.image?\begin{bmatrix}\frac{1}{tan(\frac{fovy}{2})}&space;&&space;0&space;&&space;0&space;&&space;0&space;\\0&space;&&space;\frac{1}{tan(\frac{fovy}{2})&space;\cdot&space;\frac{x}{y}}&space;&&space;0&space;&&space;0&space;\\0&space;&&space;0&space;&&space;\frac{far}{far&space;-&space;near}&space;&&space;1&space;\\0&space;&&space;0&space;&&space;-\frac{far&space;\cdot&space;near}{far&space;-&space;near}&space;&&space;0&space;\\\end{bmatrix}" title="\begin{bmatrix}\frac{1}{tan(\frac{fovy}{2})} & 0 & 0 & 0 \\0 & \frac{1}{tan(\frac{fovy}{2}) \cdot \frac{x}{y}} & 0 & 0 \\0 & 0 & \frac{far}{far - near} & 1 \\0 & 0 & -\frac{far \cdot near}{far - near} & 0 \\\end{bmatrix}" />

**Comment by walbourn** [comment]
The comments do look a little out of place...

**Comment by walbourn** [comment]
Fixed https://github.com/microsoft/DirectXMath/commit/0fc79cd30994230b4d59ed0397247be23bfa7602
