### ISSUE TITLE
More constexpr usage in DirectXMath

### ISSUE THREAD

**Issue by Zwaliebaba** [microsoft/DirectXMath#150]
Is there a possibility to include more constexpr for standard functions in DirectXMath? Especially for XMVectorSet

**Comment by walbourn** [comment]
The implementation of many of these is limited by the support of the underlying intrinsic. ``_mm_set_ps`` is not constexpr for example.

Note that for 'vector constants', the better approach is to use ``XMVECTORF32`` and friends which do support constexpr.

https://docs.microsoft.com/en-us/windows/win32/dxmath/pg-xnamath-getting-started#constant-vectors
