### ISSUE TITLE
Project version is inconsistent with release note

### ISSUE THREAD

**Issue by seungha-yang** [microsoft/DirectXMath#169]
The project version written in cmake file is [3.1.8](https://github.com/microsoft/DirectXMath/blob/dec2022/CMakeLists.txt#L6) but it's [3.18](https://github.com/microsoft/DirectXMath/releases/tag/dec2022) in release note

**Comment by nirbheek** [comment]
It would also be good to use the project version number when making tags / releases :)

**Comment by JPeterMugaas** [comment]
The version should be bumped up to 3.1.9.

**Comment by walbourn** [comment]
I have some complexities that I have to manage here because this library ships in the windows SDK. 

There is no functional change here at all.

For vcpkg, the version is the release date.
