### ISSUE TITLE
constexpr usage results in IntelliSense warnings

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXMath#44]
If you build an application using DirectXMath 3.09 with VS 2015, you get the following IntelliSense errors:

> Error (active)		constexpr function return is non-constant	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXMath.h	268	IntelliSense
	
> Error (active)		constexpr function return is non-constant	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXMath.h	269	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 39)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	50	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 71)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	80	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 96)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	105	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 120)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	129	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 144)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	153	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 168)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	177	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 193)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	202	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 217)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	226	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 241)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	250	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 265)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	274	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 290)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	300	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 325)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	338	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 360)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	371	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 387)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	398	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 414)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	425	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 440)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	451	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 466)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	477	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 492)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	503	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 524)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	535	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 555)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	566	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 586)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	597	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 617)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	628	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 648)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	659	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 679)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	690	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 706)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	718	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 732)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	744	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 758)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	770	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 784)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	796	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 811)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	822	IntelliSense	

> Error (active)		constexpr constructor fails to initialize an anonymous union (defined at line 840)	Direct3D Win32 Game2	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXPackedVector.h	851	IntelliSense	

There are no build errors/breaks in the actual build, so it's specific to the IntelliSense compiler. This does not happen with older versions of Visual C++ or DirectXMath.

**Comment by walbourn** [comment]
This is fixed in 3.10

**Comment by AbreuRodrigo** [comment]
Thanks Walbourn!!
