### ISSUE TITLE
XMCOLOR documentation on msdn is incorrect

### ISSUE THREAD

**Issue by dougbinks** [Microsoft/DirectXMath#46]
Since I can't find a way to notify msdn of their error, and since XMCOLOR is defined in DirectXMath now, I'd like to inform you that the page:

https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.xmcolor(v=vs.85).aspx

lists the b,g,r,a members of the union as being of type uint32_t rather than the correct type uint8_t.

**Comment by walbourn** [comment]
Thanks. I've submitted the bug internally..
