### ISSUE TITLE
XMMatrixRotationRollPitchYaw arguments order

### ISSUE THREAD

**Issue by nlguillemot** [Microsoft/DirectXMath#53]
The function is named `XMMatrixRotationRollPitchYaw`, but its arguments are in a different order, which is a little tricky:
```
inline XMMATRIX XM_CALLCONV XMMatrixRotationRollPitchYaw
(
    float Pitch, 
    float Yaw, 
    float Roll
)
```

Don't know if there's an easy backwards-compatible fix to this problem, but I figure it should be documented as an issue anyways.

**Comment by walbourn** [comment]
The function name indicates the order of rotation  which is roll, the pitch, then yaw. The parameter order itself is x-axis, y-axis, z-axis which makes a bit more sense with ``XMMatrixRotationRollPitchYawFromVector``.

This is also true of the ``XMQuaternionRotationRollPitchYaw`` function, as well as ``XMQuaternionRotationRollPitchYawFromVector``.
