### ISSUE TITLE
GXMVECTOR 4th parameter fixup with _vectorcall and x86?

### ISSUE THREAD

**Issue by mylosam** [microsoft/DirectXMath#54]
Looking at 3.10, DirectXMath.h line 307, GXMVECTOR is defined as const XMVECTOR& on x86 specifically, but 5th and 6th parameter fixups (HXMVECTOR) are const XMVECTOR.

Curious why we can't pass a fourth parameter in a register but we can pass fifth and sixth parameters in registers (with __vectorcall)?

thx,
Sam

```
// Fix-up for (4th) XMVECTOR parameter to pass in-register for ARM, ARM64, and x64 vector call; by reference otherwise
#if ( defined(_M_ARM) || defined(_M_ARM64) || defined(_M_HYBRID_X86_ARM64) || (_XM_VECTORCALL_ && !defined(_M_IX86) ) ) && !defined(_XM_NO_INTRINSICS_)
typedef const XMVECTOR GXMVECTOR;
#else
typedef const XMVECTOR& GXMVECTOR;
#endif

// Fix-up for (5th & 6th) XMVECTOR parameter to pass in-register for ARM64 and vector call; by reference otherwise
#if ( defined(_M_ARM64) || defined(_M_HYBRID_X86_ARM64) || _XM_VECTORCALL_ ) && !defined(_XM_NO_INTRINSICS_)
typedef const XMVECTOR HXMVECTOR;
#else
typedef const XMVECTOR& HXMVECTOR;
#endif
```

**Comment by walbourn** [comment]
I'll have to dig through my notes. I did the ``__vectorcall`` work a few years back, so I can't remember the exact scenario for x86 that triggered that.

**Comment by walbourn** [comment]
In DirectXMath 3.05 (which shipped in a preview of VS 2013), this code was:

    // Fix-up for (4th) XMVECTOR parameter to pass in-register for ARM, Xbox 360, and vector call; by reference otherwise 
    #if ( defined(_M_ARM) || defined(_XM_VMX128_INTRINSICS_) || _XM_VECTORCALL_ ) && !defined(_XM_NO_INTRINSICS_) 
    typedef const XMVECTOR GXMVECTOR; 
    #else 
    typedef const XMVECTOR& GXMVECTOR; 
    #endif 

Which would result in x86 ``_vectorcall`` passing by value as you'd surmise.

In DirectXMath 3.06, I specifically excluded this case:

    // Fix-up for (4th) XMVECTOR parameter to pass in-register for ARM, Xbox 360, and x64 vector call; by reference otherwise 
    #if ( defined(_M_ARM) || defined(_XM_VMX128_INTRINSICS_) || (_XM_VECTORCALL_ && !defined(_M_IX86) ) ) && !defined(_XM_NO_INTRINSICS_) 
    typedef const XMVECTOR GXMVECTOR; 
    #else 
    typedef const XMVECTOR& GXMVECTOR; 
    #endif

So the change was clearly intentional...

**Comment by walbourn** [comment]
Sorry, took me a while to dig into the history here...

On May 22, 2013 I made this change to DirectXMath because if I didn't, existing client code (notably DirectX Tool Kit) that made use of the various ``FXMVECTOR``, ``CXMVECTOR``, ``GXMVECTOR`` macros would fail to build in x86 ``__vectorcall`` scenarios. This was essentially an appcompat workaround for older code that was using DirectXMath 3.03's calling convention for ARM.

I think in theory I could change it now, but at the time I was trying to avoid making breaking changes to other code.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXMath/commit/cc101d2cdf5fe77766bdc83858de1ab9f54ca5e5) after some validation work.
