### ISSUE TITLE
C++ enhancements (noexcept, more constexpr, operator[] for some types)

### ISSUE THREAD

**Issue by matt77hias** [microsoft/DirectXMath#56]
- It would be nice to have an `operator[]` member method for `XMFLOAT2`, `XMFLOAT3`, `XMFLOAT4`, etc. instead of taking the address of the `x` member variable for instance. 
- All the methods of non-SIMD structs such as `XMFLOAT2`, `XMFLOAT3`, `XMFLOAT4`, etc. could be made `noexcept` and `constexpr`.

**Comment by JujiPL** [comment]
Would you also develop a bit more movable ctors and operators, please?
Sample code:
```
static_assert(std::is_nothrow_move_constructible<DirectX::XMFLOAT4>::value, "Move Ctor.");
static_assert(std::is_nothrow_move_assignable<DirectX::XMFLOAT4>::value, "Move Assign.");
```
I am sorry for posting my idea here, but it is related to this thread.

**Comment by walbourn** [comment]
What version of Visual Studio are you using? I had been relying on the VS 2015+ automatic generation of move ctors/assign operators but I may have to add ``=default`` cases...

**Comment by JujiPL** [comment]
I have the 2017 version, up to date. I understand, that implicit ctors are the best. This second static assert causes the error. It is rather not critical, but can be good in STL transformations, arrays etc.

P. S.
Thank you very much for the support and sample projects from Microsoft.

**Comment by walbourn** [comment]
Using ``=default`` for copy and move ctors and assignment solves the assert scenario above. These are also implicitly ``noexcept``.

Submitted [this commit](https://github.com/Microsoft/DirectXMath/commit/e47ad783202cc239c49bf13b27845382a9a3170e).

**Comment by walbourn** [comment]
General annotation with ``noexcept`` is in [this pull request](https://github.com/microsoft/DirectXMath/pull/97)

**Comment by walbourn** [comment]
A few more instances of ``constexpr`` added in [this pull requuest](https://github.com/microsoft/DirectXMath/pull/98). 

Note I have more C++ things like ``operator[]`` for vectors in [SimpleMath](https://github.com/microsoft/DirectXTK/wiki/SimpleMath) types like ``Vector4``.
