### ISSUE TITLE
XMVector3ProjectStream crashes on X86 for _DEBUG builds

### ISSUE THREAD

**Issue by blloyd75** [Microsoft/DirectXMath#58]
With the 2017.3  visual studio compiler, using DirectX::XMVector3ProjectStream in will cause a crash on X86 on debug.  Because release inlines this, it is not visible in release.
The
FXMMATRIX     Projection, 
parameter resolves to XMMATRIX (not a reference) because the _XM_VECTORCALL_ convention is in play.  However, XMMATRIX is a 16 byte aligned entity and visual studio has an 8 byte max::max_align_t.  Later usage in SSE crashes.  Reading the dissambly at the crash shows that the variable is 8 byte aligned but not 16 byte aligned.

2017.2 does not expose this bug.

**Comment by walbourn** [comment]
This seems to be another manifestation of [this compiler bug](https://github.com/Microsoft/DirectXMath/issues/54)

**Comment by walbourn** [comment]
I'm not able to reproduce this bug with VS 2017 (15.4). Can you confirm it still repros with the [latest update](https://blogs.msdn.microsoft.com/chuckw/2017/08/14/visual-studio-2017-15-3-update/)? Also, have you tried ``/Zi`` vs. ``/ZI``?

**Comment by blloyd75** [comment]
15.4 no longer crashes debug builds using this function.  I didn't compare byte codes, but it appears to be fixed.
