### ISSUE TITLE
XMConvertFloatToHalf undefined behavior: right shift by the width of the operand

### ISSUE THREAD

**Issue by alek314** [Microsoft/DirectXMath#60]
XMConvertFloatToHalf(0) will enter the denormalized half branch, where local variable "Shift" is assigned value 113, which should be less than 32.
This will trigger a warning on Clang Undefined Behavior Sanitizer.

**Comment by walbourn** [comment]
Looks like I just need a test for IValue == 0.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXMath/commit/bcc9236ae5cfb305a6593c9cac36e753259fd231)

**Comment by walbourn** [comment]
This is in DirectXMath 3.12
