### ISSUE TITLE
Request: add NEON half/float conversion support

### ISSUE THREAD

**Issue by alek314** [Microsoft/DirectXMath#68]
On pc, we already have F16C, on ARM, vcvt_f32_f16 and vcvt_f16_f32 should do the job?
Some background: On ios device we used to do skeleton animation on the cpu, using DirectXMath. Then we offload this process to gpu using Metal compute shader, and get a huge performance boost(A8+ device). I am wondering if I should do the same on Android device. If the answer is Yes, then this request become obsolete. 

Thank you.

**Comment by walbourn** [comment]
F16C support in DirectXMath is enabled specifically for Xbox One and when building with ``/arch:AVX2``. See [this blog post](https://blogs.msdn.microsoft.com/chuckw/2012/09/11/directxmath-f16c-and-fma/).

DirectXMath's ARM 32-bit implementation assumes ARMv7 ARM-NEON and VFPv3. Half-precision support here is not widely supported.

DirectXMath's ARM 64-bit implementation assumes ARMv8 ARM-NEON and VFPv4. Here I can and do make use of ``vcvt_f32_f16`` and ``vcvt_f32_f16``
