### ISSUE TITLE
assert(!XMVector3Equal(Axis, XMVectorZero())); hits only for _XM_NO_INTRINSICS_

### ISSUE THREAD

**Issue by jamesford42** [microsoft/DirectXMath#77]
When the value `{-inf,-inf,-inf}` is passed in as the `Axis` argument to `XMMatrixRotationAxis`, I have noticed that its assertion will only hit for the _XM_NO_INTRINSICS_ path. 

This seems like undesirable behavior, considering that the assert itself is not within an ifdef.

**Comment by walbourn** [comment]
What compiler/version are you using?

**Comment by jamesford42** [comment]
visual studio 2017
But, the issue is that the assert itself is within an _XM_NO_INTRINSICS_ ifdef block, so...

**Comment by walbourn** [comment]
I've definitely had issues with ``/fp:fast`` and specials, but it's generally a preferred way to go for performance. I'll see what I can do.

**Comment by walbourn** [comment]
The function also has an assert:

```
assert(!XMVector3IsInfinite(Axis));
```

That one should be firing for your case.

There were some issues in VS 2019 RTM, Update 1, and Update 2 and with DirectXMath prior to version 3.14 when I added ``#pragma float_control(precise, on)`` around ``XMVector3IsNaN``.

I'll see if I can find a #pragma for clang/LLVM for this, but I don't see one outside of clang-cl.
