### ISSUE TITLE
Equivalent to glm::value_ptr?

### ISSUE THREAD

**Issue by juanPabloRamosWork** [Microsoft/DirectXMath#79]
`
DirectX::XMFLOAT4 const clear_color(0.4f, 0.6f, 0.9f, 1.0f);
command_list_->ClearRenderTargetView(rtv, reinterpret_cast<FLOAT const *>(&clear_color), 0, nullptr);
`
Is there an alternative to this reinterpret_cast? 
GLM has value_ptr : https://stackoverflow.com/questions/21096511/how-to-convert-a-glmvec4float-to-a-glfloat

Does DirectXMath also have an alternative?

**Comment by walbourn** [comment]
The ``DirectXColors.h`` header uses ``XMVECTORF32`` for this purpose...

**Comment by walbourn** [comment]
For more "C++ magic behavior" like this, I have [SimpleMath](https://github.com/Microsoft/DirectXTK/wiki/SimpleMath) where ``Vector2``, ``Vector3``, and ``Vector4`` have more implicit conversions as well as some Standard Library overloads for use in containers.

You should also take some time to read through the [DirectXMath Programmer's Guide](https://docs.microsoft.com/en-us/windows/desktop/dxmath/ovw-xnamath-progguide) to get some background on the intended use of ``XMFLOATx`` vs. ``XMVECTOR``, etc.
