### ISSUE TITLE
XMVector2TransformStream and XMVector3TransformStream always provide the result in form of 4D vector

### ISSUE THREAD

**Issue by mr-pesh** [Microsoft/DirectXMath#80]
_XMVector**X**TransformStream_ functions look as a quite elegant solution for transforming huge sets of vectors (e.g. lists of vertices), and looks like one of it's best applications - performing transformation on vectors that are packed in a binary stream. The example can look like this:
```cpp
#include <memory>
using namespace std;

#include <DirectXMath.h>
....
class Renderer;
...
unique_ptr<uint8_t> ReadObjectFromFile(const char *fileName);
...
int main()
{
    Renderer renderer;
    unique_ptr<uint8_t> my3dObject = ReadObjectFromFile("my3dObject.obj");
    renderer.draw(my3dObject.get());

    auto rotatedObject = make_unique<uint8_t>(4096);

    XMVector3TransformStream(
        (XMFLOAT3*)rotatedObject.get(), sizeof(XMFLOAT3),
        (XMFLOAT3*)my3dObject.get(), sizeof(XMFLOAT3),
        renderer.getRotationMatrix("x", 90)
    );

    renderer.draw(rotatedObject.get());
}
```
Unfortunately, this code will not work, since _XMVector3TransformStream_ function expects the pointer to **XMFLOAT4**, so if I want to transform an array of 2- or 3D vectors, the result will always be the set of 4D vectors.
It's a bit confusing, and leads to a memory overhead on big sets of vectors. The most interesting thing here is that the actual implementation supports a way of bypassing this restriction - you can specify the _OutputStride_ parameter to match the size of the exact vector you need. In the mentioned above example case it will look like
```cpp
XMVector3TransformStream(
    (XMFLOAT4*)rotatedObject.get(), sizeof(XMFLOAT3),
    (XMFLOAT3*)my3dObject.get(), sizeof(XMFLOAT3),
    renderer.getRotationMatrix("x", 90)
);
```
which is a bit misleading, but still is a kind of valid behavior.
The only problem here are `assert()` macros in _XMVector**X**TransformStream_ implementation, that check the _InputStride_ and _OutputStride_ parameters, and on debug builds they crash the application trying to use the hack.

So my actual questions are:
* Are you planning to support **XMFLOAT3** to **XMFLOAT3** stream transformations?
* Is there a way to correctly utilize the desired behavior?

**Comment by walbourn** [comment]
Technically speaking the result of ``XMVector3TransformStream`` is not guaranteed to fit into an ``XMFLOAT3`` since it takes a general matrix so the result may not have a ``w`` of 1 hence why the output must be ``XMFLOAT4``.

This is also why there is a ``XMVector3TransformCoordStream`` which performs the homogenous divide which ensures the result is a ``w`` of 1 so it can output ``XMFLOAT3``. That's probably the one you want to use.

There is  also a ``XMVector3TransformNormalStream`` which can write a ``XMFLOAT3`` because it ignores the third row of the matrix.
