### ISSUE TITLE
XMQuaternionToAxisAngle(...) not returning the unit axis

### ISSUE THREAD

**Issue by ChrisKing340** [Microsoft/DirectXMath#81]
XMQuaternionToAxisAngle(XMVECTOR* pAxis, float*    pAngle, FXMVECTOR  Q) does not convert the quaternion coefficients back to a unit vector.  
Since XMQuaternionRotationNormal(FXMVECTOR NormalAxis, float Angle) and XMQuaternionRotationAxis(FXMVECTOR Axis, float Angle) both pass in a unit vector and converts to quaternion coefficients, why not have XMQuaternionToAxisAngle return the unit vector for axis?  What is the purpose of returning the quaternion coefficients instead that still needs to be scaled by 1/sin(angle/2)?

**Comment by walbourn** [comment]
This function implementation hasn't changed since xboxmath. I think it assumes the input is a normalized quaternion so that the returned axis is a normalized 3D vector.

**Comment by walbourn** [comment]
So looking at the test code some more, the problem I think is that a lot of the older functions in the library originally assumed that for 3-vectors, you'd just ignore the ``.w`` component of the ``XMVECTOR`` result. The test code certainly ignores the 4th element.

As such, I should probably modify the code to ensure the last element is a ``1`` to avoid giving the impression that it's a non-normalized 4-vector.

**Comment by ChrisKing340** [comment]
I want to draw my quaternions and looking for a function that returns the axis and rotation.  DirectX::XMQuaternionRotationNormal(FXMVECTOR NormalAxis, float Angle) seems like the one intended for this.  Currently, my quaternion class (contains a XMVECTOR) has a work around to get the axis:
```
			if (*this) // bool conversion, rotation to apply and not zero (or near zero)
			{
				float sinHalfAngle = DirectX::XMScalarSin(DirectX::XMScalarACos(GetW())); 
				float3 scale(sinHalfAngle); // replicates float in each of x, y, z
				return xyz / scale;
			}
```
Looking at the library to see if there was an intended way to transform back to vector space.

**Comment by ChrisKing340** [comment]
Just realized what you meant Mark, I need to normalize just the vector3 portion without the 4th.
