### ISSUE TITLE
row major matrix

### ISSUE THREAD

**Issue by 3DdeepAI** [Microsoft/DirectXMath#82]
I found this information:  [..]"DirectXMath uses row-major matrices"[..]
on page https://docs.microsoft.com/en-us/windows/desktop/api/directxmath/ns-directxmath-xmmatrix

and I looked into XMMatrixTranslation on page
https://github.com/Microsoft/DirectXMath/blob/16542826084488354f9495ded1bec6cba8b2a00b/Inc/DirectXMathMatrix.inl#L1154
which leads to a matrix layout like this:
```
1  0  0  0
0  1  0  0
0  0  1  0 
x  y  z  1
```
Its described here also this way: https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/row-major-vs-column-major-vector

But on this page http://www.mindcontrol.org/~hplus/graphics/matrix-layout.html
a **row-major** matrix is described this way:
```
1  0  0  x
0  1  0  y
0  0  1  z 
0  0  0  1
```
I yet assumed that "rows" are horizontal vectors and "columns" are vertical vectors.
Is it a different style of terminology?
So why are both defined as "row-major" although they have a different layout?

**Comment by walbourn** [comment]
I don't see on the mindcontrol.org site the layout you describe. That's a "column-major" matrix if it's a translation.

**Comment by 3DdeepAI** [comment]
it says: 
_they could be stored in the order m11 m12 m13 m14 m21 ..., or they could be stored in the order m11 m21 m31 m41 m12 ... The first version is called "row major" because you can view it as storing one row at a time. The second version is called "column major"_ 

The first there is 
```
      m11 m12 m13 m14    x
      m21 m22 m23 m24    y
      m31 m32 m33 m34    z
      m41 m42 m43 m44    1
     Case 1: column vector on the right
```

**Comment by 3DdeepAI** [comment]
And i found this:

The translation matrix in line 624  of NVIDIA OptiX uses elements 3, 7, 11 in a float[16] array   (which is m14,m24,m34); see:
https://docs.nvidia.com/gameworks/content/gameworkslibrary/optix/optixapireference/optixu__matrix__namespace_8h_source.html

[..]The data array is stored in **row-major** order.[..]
https://docs.nvidia.com/gameworks/content/gameworkslibrary/optix/optixapireference/classoptix_1_1_matrix.html

And so layout also there is considered row-major
```
      m11 m12 m13 m14   
      m21 m22 m23 m24   
      m31 m32 m33 m34   
      m41 m42 m43 m44   
```

See the layout also here:
https://raytracing-docs.nvidia.com/optix/api/html/group___transform_node.html#ga23f0e226bcad32a8e5804d2f1476f559

_Here, the translational elements a14, a24, and a34 are at the 4th, 8th, and 12th position the matrix array. If the supplied matrices are in column-major format, a non-0 transpose flag can be used to trigger an automatic transpose of the input matrices._

**Comment by walbourn** [comment]
Really it comes down to how the memory is laid out. For DirectXMath we use row-major matrices so the matrix is laid out in memory like this:

```
struct
{
    float _11, _12, _13, _14;
    float _21, _22, _23, _24;
    float _31, _32, _33, _34;
    float _41, _42, _43, _44;
};
```

Which in memory is:

```
_11
_12
_13
_14
_21
_22
_23
_24
_31
_32
_33
_34
_41
_42
_43
_44;
```

In row-major, the first four elements are the 1st 'row' of the matrix.

In column-major, the first four elements are the 1st 'column'.

**Comment by 3DdeepAI** [comment]
yes, but that is exactly why I asked the question, cause in OptiX the matrices are also **row-major** and the  memory is laid out the same way:
float matrix[4*4] = { a11, a12, a13, a14, a21, a22, a23, a24, a31, a32, a33, a34, a41, a42, a43, a44 };
but there **translation** is set in a14, a24, and a34   and not in the last row[3] as in DirectXmath.

However, I simply transpose it (and do the LH to RH conversion).

Thank you.
