### ISSUE TITLE
Replace malloc.h with stdlib.h

### ISSUE THREAD

**Issue by Cryru** [microsoft/DirectXMath#85]
In DirectXMath.h on line 103 malloc.h is imported. However this header is not present on all systems, causing compilation to fail. I'd like to suggest swapping it out for stdlib.h which being a standard header should make the library more portable.

Opinions?

**Comment by matt77hias** [comment]
Prefer cstdlib.

**Comment by Cryru** [comment]
Well it seems "sal.h" header already makes the library non-portable, so this change won't do all that much. Also I can't find why it's being imported in the first case - it seems it isn't being used at all.

**Comment by walbourn** [comment]
SAL annotation is required by Microsoft's [Security Development Lifecycle](https://www.microsoft.com/en-us/securityengineering/sdl/practices).

The lack of a 'sal.h' header is easily resolved: You just need a header that defines those symbols to blank somewhere in your system path:

```
#define _In_
#define _Out_


```

**Comment by walbourn** [comment]
I'm looking at the malloc.h issue. I'm not sure that header is even needed anymore at all, but I have to make sure all contexts where my header is used isn't broken by removing it.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXMath/commit/775411a74e65e99cf7d4b83b2377bca7d5b987aa)
