### ISSUE TITLE
ARM NEON intrinsics not fully type safe

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXMath#87]
The official ARM-NEON intrinsics are very 'typeful', but most implementations don't really use distinct types for every possible typedef so they can be assigned 'incorrectly' fairly easily.

The clang/LLVM toolset found a number of cases of assigning the 'wrong' types compared to Visual C++, but a number of issues remain based on visual inspection. This is mostly an issue for future compatibility as toolsets tighten up the spec:

A few uses of the VTBL instrinsics:

```
uint8x8x2_t tbl;
tbl.val[0] = vget_low_f32(V);
tbl.val[1] = vget_high_f32(V);
->
uint8x8x2_t tbl;
tbl.val[0] = vreinterpret_u8_f32(vget_low_f32(V));
tbl.val[1] = vreinterpret_u8_f32(vget_high_f32(V));
```

```
const uint8x8_t rL = ...
const uint8x8_t rH = ...
return vcombine_f32( rL, rH );
->
const uint8x8_t rL = ...
const uint8x8_t rH = ...
return vcombine_f32( vreinterpret_f32_u8(rL), vreinterpret_f32_u8(rH) );
```

There's similar issues with vzip usage.

When using the vceq and other comparision intrinsics:

```
uint32x2_t VEqualsZero = vceq_f32( vTemp, zero );
…
Result = vbsl_f32( VEqualsZero, zero, Result );
->
float32x2_t VEqualsZero = vinterpret_f32_u32(vceq_f32( vTemp, zero ));
…
Result = vbsl_f32( VEqualsZero, zero, Result );
```

**Comment by walbourn** [comment]
Still looking for a better conforming toolset as I don't have access to armclang

**Comment by zhaijialong** [comment]
We found the same issue with NDK gcc. 

There are lots of implicit conversions of float32x4/int32x4/uint32x4 in current directxmath code. That compiles with NDK clang, but failed with NDK gcc. Really wish that can be fixed. 

Thanks.

**Comment by walbourn** [comment]
@zhaijialong  Thanks. I'm able to set this environment up locally now. It will take a while to work through them all, but I'm able to get compiler validation now.

**Comment by walbourn** [comment]
See [this PR](https://github.com/microsoft/DirectXMath/pull/115)
